project_id = "vfxpjubzliquatciwfpd"

[functions.revenue-insights]
verify_jwt = false

[functions.billing_npt_insights]
verify_jwt = false

[functions.parse-filter-query]
verify_jwt = false

[functions.budget-variance-alerts]
verify_jwt = false
